"""date-quantity in previous association table

Revision ID: 17d3b1fc8282
Revises: a2525cd2cc07
Create Date: 2022-03-22 20:15:44.510231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d3b1fc8282'
down_revision = 'a2525cd2cc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_order',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'order_id')
    )
    op.create_index(op.f('ix_link_order_order_date'), 'link_order', ['order_date'], unique=False)
    op.create_index(op.f('ix_link_order_quantity'), 'link_order', ['quantity'], unique=False)
    op.drop_table('ProfileOrder')
    op.drop_index('ix_order_quantity_order_name', table_name='order_quantity')
    op.drop_index('ix_order_quantity_quantity', table_name='order_quantity')
    op.drop_table('order_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_quantity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_quantity_quantity', 'order_quantity', ['quantity'], unique=False)
    op.create_index('ix_order_quantity_order_name', 'order_quantity', ['order_name'], unique=False)
    op.create_table('ProfileOrder',
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.drop_index(op.f('ix_link_order_quantity'), table_name='link_order')
    op.drop_index(op.f('ix_link_order_order_date'), table_name='link_order')
    op.drop_table('link_order')
    # ### end Alembic commands ###
