"""empty message

Revision ID: 26d6c5aee2b4
Revises: 85e6eb64ea3e
Create Date: 2022-02-09 01:21:53.593778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d6c5aee2b4'
down_revision = '85e6eb64ea3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfileFumo',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('fumo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fumo_id'], ['fumo.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.drop_table('fumos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fumos',
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('fumo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fumo_id'], ['fumo.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.drop_table('ProfileFumo')
    # ### end Alembic commands ###
