"""empty message

Revision ID: 647b0519fcd8
Revises: 
Create Date: 2022-02-06 00:25:59.680428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647b0519fcd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fumo_name'), 'fumo', ['name'], unique=False)
    op.create_index(op.f('ix_fumo_price'), 'fumo', ['price'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_fumo_price'), table_name='fumo')
    op.drop_index(op.f('ix_fumo_name'), table_name='fumo')
    op.drop_table('fumo')
    # ### end Alembic commands ###
