"""changed name from fum to order

Revision ID: a5bbeabc1035
Revises: 26d6c5aee2b4
Create Date: 2022-02-24 09:22:27.734329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bbeabc1035'
down_revision = '26d6c5aee2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_price'), ['price'], unique=False)

    op.create_table('ProfileOrder',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.drop_table('ProfileFumo')
    with op.batch_alter_table('fumo', schema=None) as batch_op:
        batch_op.drop_index('ix_fumo_name')
        batch_op.drop_index('ix_fumo_price')

    op.drop_table('fumo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fumo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fumo', schema=None) as batch_op:
        batch_op.create_index('ix_fumo_price', ['price'], unique=False)
        batch_op.create_index('ix_fumo_name', ['name'], unique=False)

    op.create_table('ProfileFumo',
    sa.Column('profile_id', sa.INTEGER(), nullable=True),
    sa.Column('fumo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fumo_id'], ['fumo.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], )
    )
    op.drop_table('ProfileOrder')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_price'))
        batch_op.drop_index(batch_op.f('ix_order_name'))

    op.drop_table('order')
    # ### end Alembic commands ###
